apiVersion: v2
name: mongodb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0    #The version of the Helm chart itself. It can be customized based on your project's versioning conventions
appVersion: "1.0.0"   #The version of the application that the Helm chart is deploying, we can also use 2.5.1-alpha.
