apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  PSQL_PASSWORD: lokesh123 # Customize the values below to set your desired usernames and passwords
  JWT_SECRET: sarcasm # Customize the values below to set your desired usernames and passwords
type: Opaque

