apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGODB_VIDEOS_URI: "mongodb://lokesh:lokesh123@mongodb:27017/videos?authSource=admin"
  MONGODB_MP3S_URI: "mongodb://lokesh:lokesh123@mongodb:27017/mp3s?authSource=admin"

#"mongodb://username:password@mongodb:27017/mp3s?authSource=admin"
#replace with mongodb username password
