apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "timepassdevops@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "jxng uxak zewp msdb" #enter your email app password which was created in email notification and 2factor authentication step.
type: Opaque

